name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  RESOURCE_GROUP: "1-ff8a1c0c-playground-sandbox"
  CLUSTER_NAME: "leonsaks101"
  DEPLOYMENT_MANIFEST_PATH: "deployment.yaml"

#permissions:
#  contents: read

jobs:
  build-java:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Show me the Jar location
      run: |
        hostname
        pwd
        ls -ltr
        ls -ltr $PWD/build/libs

    - name: Build the Docker Image
      run: |
        docker build . --file Dockerfile --tag leepereira/course-api:0.0.7
        docker images
        container_id=$(docker run -d -p 8080:8080 leepereira/course-api:0.0.7)
        docker ps
        docker logs $container_id
        
    - name : Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name : Docker Push
      run: | 
        docker push leepereira/course-api:0.0.7


    # this is the CD part and I think we should separate this out to a different workflow file
    - name: Azure Login
      run: az login --service-principal --username ${{ secrets.AZURE_SP_CLIENT_ID }} --password ${{ secrets.AZURE_SP_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_SP_TENANT_ID }}

      # Use kubelogin to configure your kubeconfig for Azure auth
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

      # Deploys application based on given manifest file
    - name: Deploys application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
        images: |
          leepereira/course-api:0.0.7
        

