# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


permissions:
  contents: read

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Show me the Jar
      run: |
        pwd
        ls -ltr
        ls -ltr /home/runner/work/course-api-personal-github-gha-explore/course-api-personal-github-gha-explore/build/libs

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-app-java:1.1.1
#
#    - name: Build & Push to Docker Hub
#      uses: opspresso/action-docker@master
#      with:
#        args: --docker
#      env:
#        USERNAME: ${{ secrets.DOCKER_USERNAME }}
#        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        TAG_NAME: "v0.0.1"
#        BUILDX: "true"



#    - name: Build and Push Docker Image
#      uses: mr-smithers-excellent/docker-build-push@v4
#      with:
#        image: leepereira/course-api:latest
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}


